"""Adicionado Usuario e Relacionamentos

Revision ID: 051ce657690b
Revises: 6a726a0a247d
Create Date: 2023-03-12 16:30:36.477189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051ce657690b'
down_revision = '6a726a0a247d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_usuario', 'usuario', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_constraint('fk_usuario', type_='foreignkey')

    # ### end Alembic commands ###
